#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetWeb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class betdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBetData(BetData instance);
    partial void UpdateBetData(BetData instance);
    partial void DeleteBetData(BetData instance);
    #endregion
		
		public betdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataSourceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public betdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public betdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public betdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public betdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BetData> BetData
		{
			get
			{
				return this.GetTable<BetData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BetData")]
	public partial class BetData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _MatchID;
		
		private string _Num;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _Time;
		
		private int _L_ID;
		
		private string _L_CN;
		
		private int _H_ID;
		
		private string _H_CN;
		
		private int _A_ID;
		
		private string _A_CN;
		
		private string _Source_Odds;
		
		private string _Current_Odds;
		
		private string _Flag;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _UpdateDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMatchIDChanging(int value);
    partial void OnMatchIDChanged();
    partial void OnNumChanging(string value);
    partial void OnNumChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnTimeChanging(System.TimeSpan value);
    partial void OnTimeChanged();
    partial void OnL_IDChanging(int value);
    partial void OnL_IDChanged();
    partial void OnL_CNChanging(string value);
    partial void OnL_CNChanged();
    partial void OnH_IDChanging(int value);
    partial void OnH_IDChanged();
    partial void OnH_CNChanging(string value);
    partial void OnH_CNChanged();
    partial void OnA_IDChanging(int value);
    partial void OnA_IDChanged();
    partial void OnA_CNChanging(string value);
    partial void OnA_CNChanged();
    partial void OnSource_OddsChanging(string value);
    partial void OnSource_OddsChanged();
    partial void OnCurrent_OddsChanging(string value);
    partial void OnCurrent_OddsChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    #endregion
		
		public BetData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatchID", DbType="Int NOT NULL")]
		public int MatchID
		{
			get
			{
				return this._MatchID;
			}
			set
			{
				if ((this._MatchID != value))
				{
					this.OnMatchIDChanging(value);
					this.SendPropertyChanging();
					this._MatchID = value;
					this.SendPropertyChanged("MatchID");
					this.OnMatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_ID", DbType="Int NOT NULL")]
		public int L_ID
		{
			get
			{
				return this._L_ID;
			}
			set
			{
				if ((this._L_ID != value))
				{
					this.OnL_IDChanging(value);
					this.SendPropertyChanging();
					this._L_ID = value;
					this.SendPropertyChanged("L_ID");
					this.OnL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_CN", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string L_CN
		{
			get
			{
				return this._L_CN;
			}
			set
			{
				if ((this._L_CN != value))
				{
					this.OnL_CNChanging(value);
					this.SendPropertyChanging();
					this._L_CN = value;
					this.SendPropertyChanged("L_CN");
					this.OnL_CNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_ID", DbType="Int NOT NULL")]
		public int H_ID
		{
			get
			{
				return this._H_ID;
			}
			set
			{
				if ((this._H_ID != value))
				{
					this.OnH_IDChanging(value);
					this.SendPropertyChanging();
					this._H_ID = value;
					this.SendPropertyChanged("H_ID");
					this.OnH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_CN", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string H_CN
		{
			get
			{
				return this._H_CN;
			}
			set
			{
				if ((this._H_CN != value))
				{
					this.OnH_CNChanging(value);
					this.SendPropertyChanging();
					this._H_CN = value;
					this.SendPropertyChanged("H_CN");
					this.OnH_CNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_ID", DbType="Int NOT NULL")]
		public int A_ID
		{
			get
			{
				return this._A_ID;
			}
			set
			{
				if ((this._A_ID != value))
				{
					this.OnA_IDChanging(value);
					this.SendPropertyChanging();
					this._A_ID = value;
					this.SendPropertyChanged("A_ID");
					this.OnA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_CN", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string A_CN
		{
			get
			{
				return this._A_CN;
			}
			set
			{
				if ((this._A_CN != value))
				{
					this.OnA_CNChanging(value);
					this.SendPropertyChanging();
					this._A_CN = value;
					this.SendPropertyChanged("A_CN");
					this.OnA_CNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source_Odds", DbType="NVarChar(500)")]
		public string Source_Odds
		{
			get
			{
				return this._Source_Odds;
			}
			set
			{
				if ((this._Source_Odds != value))
				{
					this.OnSource_OddsChanging(value);
					this.SendPropertyChanging();
					this._Source_Odds = value;
					this.SendPropertyChanged("Source_Odds");
					this.OnSource_OddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_Odds", DbType="NVarChar(500)")]
		public string Current_Odds
		{
			get
			{
				return this._Current_Odds;
			}
			set
			{
				if ((this._Current_Odds != value))
				{
					this.OnCurrent_OddsChanging(value);
					this.SendPropertyChanging();
					this._Current_Odds = value;
					this.SendPropertyChanged("Current_Odds");
					this.OnCurrent_OddsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="NChar(10)")]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
