<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="betdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Persist Security Info=True;User ID=adp" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BetData" Member="BetData">
    <Type Name="BetData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MatchID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="L_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="L_CN" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="H_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="H_CN" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="A_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="A_CN" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Source_Odds" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Current_Odds" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Flag" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>